In [1]:
# Importing Dependencies
import pandas as pd
import numpy as np

In [2]:
# Bringing in Uncleaned CSV's
csv1 = "Resources/JC-201908-citibike-tripdata.csv"
csv2 = "Resources/JC-202008-citibike-tripdata.csv"
bike_trip_2019 = pd.read_csv(csv1)
bike_trip_2020 = pd.read_csv(csv2)

In [3]:
# Viewing the 2019 Data
bike_2019_df = bike_trip_2019
bike_2019_df.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.71654,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.72163,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1

In [4]:
# Viewing the 2020 Data
bike_2020_df = bike_trip_2020
bike_2020_df.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42303,Customer,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,Subscriber,1996,1

In [5]:
# Deleting Columns
del bike_2019_df['usertype']
del bike_2020_df['usertype']

In [6]:
bike_2019_df.head(5)
bike_2020_df.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42303,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,1996,1
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,1984,2
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42310,1993,1
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42346,1995,2

In [7]:
# Checking Type of Values
bike_2019_df.dtypes
bike_2020_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
birth year                   int64
gender                       int64
dtype: object

In [8]:
# Changing The Type of Values for the Gender Column
bike_2019_df['gender'] = bike_2019_df['gender'].astype(str)
bike_2020_df['gender'] = bike_2020_df['gender'].astype(str)

In [9]:
# Changing the Numeric Gender Values to Actual Gender Values For The 2019 CSV
gender_check_2019 = bike_2019_df['gender']
changed_2019_male = gender_check_2019.replace('1', 'Male')
changed_2019_female = changed_2019_male.replace('2', 'Female')
changed_2019_unknown = changed_2019_female.replace('0', 'Unknown')
bike_2019_df['gender'] = changed_2019_unknown
bike_2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,1980,Male
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,1996,Male
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,1991,Male
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717732,-74.043845,29598,1988,Male
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,1960,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48706,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,1988,Male
48707,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717732,-74.043845,29679,1997,Male
48708,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,1997,Female
48709,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,1998,Male
48710,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717732,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,1992,Male

In [10]:
# Changing the Numeric Gender Values to Actual Gender Values For The 2020 CSV
gender_check_2020 = bike_2020_df['gender']
changed_2020_male = gender_check_2020.replace('1', 'Male')
changed_2020_female = changed_2020_male.replace('2', 'Female')
changed_2020_unknown = changed_2020_female.replace('0', 'Unknown')
bike_2020_df['gender'] = changed_2020_unknown
bike_2020_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42303,1994,Female
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,1996,Male
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,1984,Female
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42310,1993,Male
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42346,1995,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,1977,Male
43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,1986,Male
43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,1960,Male
43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,1994,Male
43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,1984,Female

In [11]:
# Calculating Biker's Age's 
current_year = 2024

birth_year_2019 = bike_2019_df['birth year']
age = current_year - birth_year_2019
bike_2019_df['age'] = age

birth_year_2020 = bike_2020_df['birth year']
age = current_year - birth_year_2020
bike_2020_df['age'] = age

In [12]:
# Rearranging the Columns
bike_2019_df_organized = bike_2019_df[["bikeid",
                                       "gender",
                                       "birth year",
                                       "age",
                                       "tripduration",
                                       "start station id",
                                       "start station name",
                                       "start station latitude",
                                       "start station longitude",
                                       "starttime",
                                       "end station id",
                                       "end station name", 
                                       "end station latitude",
                                       "end station longitude",
                                       "stoptime"]]

bike_2020_df_organized = bike_2020_df[["bikeid",
                                       "gender",
                                       "birth year",
                                       "age",
                                       "tripduration",
                                       "start station id",
                                       "start station name",
                                       "start station latitude",
                                       "start station longitude",
                                       "starttime",
                                       "end station id",
                                       "end station name", 
                                       "end station latitude",
                                       "end station longitude",
                                       "stoptime"]]

bike_2019_df_organized.head(5)
bike_2020_df_organized.head(5)

,bikeid,gender,birth year,age,tripduration,start station id,start station name,start station latitude,start station longitude,starttime,end station id,end station name,end station latitude,end station longitude,stoptime
0,42303,Female,1994,30,561,3185,City Hall,40.717732,-74.043845,2020-08-01 00:00:16.5960,3185,City Hall,40.717732,-74.043845,2020-08-01 00:09:38.5610
1,44989,Male,1996,28,236,3186,Grove St PATH,40.719586,-74.043117,2020-08-01 00:00:46.3900,3270,Jersey & 6th St,40.725289,-74.045572,2020-08-01 00:04:42.8890
2,41696,Female,1984,40,384,3186,Grove St PATH,40.719586,-74.043117,2020-08-01 00:02:38.9250,3203,Hamilton Park,40.727596,-74.044247,2020-08-01 00:09:03.7590
3,42310,Male,1993,31,1302,3185,City Hall,40.717732,-74.043845,2020-08-01 00:03:27.0270,3185,City Hall,40.717732,-74.043845,2020-08-01 00:25:09.2120
4,42346,Female,1995,29,5561,3185,City Hall,40.717732,-74.043845,2020-08-01 00:03:57.4810,3185,City Hall,40.717732,-74.043845,2020-08-01 01:36:38.5000

In [13]:
# Renaming the Columns
bike_2019_renamed_df = bike_2019_df_organized.rename(columns={"bikeid":"Bike ID", 
                                                              "gender":"Gender",
                                                              "birth year":"Birth Year",
                                                              "age":"Age",
                                                              "tripduration":"Trip Duration",
                                                              "start station id":"Start Station ID",
                                                              "start station name":"Start Station Name",
                                                              "start station latitude":"Start Station Latitude",
                                                              "start station longitude":"Start Station Longitude",
                                                              "starttime":"Start Time",
                                                              "end station id":"End Station ID",
                                                              "end station name":"End Station Name",
                                                              "end station latitude":"End Station Latitude",
                                                              "end station longitude":"End Station Longitude",
                                                              "stoptime":"Stop Time"})

bike_2020_renamed_df = bike_2020_df_organized.rename(columns={"bikeid":"Bike ID", 
                                                              "gender":"Gender",
                                                              "birth year":"Birth Year",
                                                              "age":"Age",
                                                              "tripduration":"Trip Duration",
                                                              "start station id":"Start Station ID",
                                                              "start station name":"Start Station Name",
                                                              "start station latitude":"Start Station Latitude",
                                                              "start station longitude":"Start Station Longitude",
                                                              "starttime":"Start Time",
                                                              "end station id":"End Station ID",
                                                              "end station name":"End Station Name",
                                                              "end station latitude":"End Station Latitude",
                                                              "end station longitude":"End Station Longitude",
                                                              "stoptime":"Stop Time"})



bike_2019_renamed_df
bike_2020_renamed_df

,Bike ID,Gender,Birth Year,Age,Trip Duration,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,Start Time,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Stop Time
0,42303,Female,1994,30,561,3185,City Hall,40.717732,-74.043845,2020-08-01 00:00:16.5960,3185,City Hall,40.717732,-74.043845,2020-08-01 00:09:38.5610
1,44989,Male,1996,28,236,3186,Grove St PATH,40.719586,-74.043117,2020-08-01 00:00:46.3900,3270,Jersey & 6th St,40.725289,-74.045572,2020-08-01 00:04:42.8890
2,41696,Female,1984,40,384,3186,Grove St PATH,40.719586,-74.043117,2020-08-01 00:02:38.9250,3203,Hamilton Park,40.727596,-74.044247,2020-08-01 00:09:03.7590
3,42310,Male,1993,31,1302,3185,City Hall,40.717732,-74.043845,2020-08-01 00:03:27.0270,3185,City Hall,40.717732,-74.043845,2020-08-01 00:25:09.2120
4,42346,Female,1995,29,5561,3185,City Hall,40.717732,-74.043845,2020-08-01 00:03:57.4810,3185,City Hall,40.717732,-74.043845,2020-08-01 01:36:38.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,44787,Male,1977,47,162,3186,Grove St PATH,40.719586,-74.043117,2020-08-31 23:43:15.8540,3279,Dixon Mills,40.721630,-74.049968,2020-08-31 23:45:58.4550
43263,19153,Male,1986,38,400,3481,York St,40.716490,-74.041050,2020-08-31 23:46:19.9130,3187,Warren St,40.721124,-74.038051,2020-08-31 23:53:00.3610
43264,42434,Male,1960,64,288,3195,Sip Ave,40.730897,-74.063913,2020-08-31 23:47:16.8680,3194,McGinley Square,40.725340,-74.067622,2020-08-31 23:52:05.5550
43265,44226,Male,1994,30,199,3195,Sip Ave,40.730897,-74.063913,2020-08-31 23:50:37.2650,3194,McGinley Square,40.725340,-74.067622,2020-08-31 23:53:56.9490
43266,42437,Female,1984,40,333,3211,Newark Ave,40.721525,-74.046305,2020-08-31 23:55:30.8050,3270,Jersey & 6th St,40.725289,-74.045572,2020-09-01 00:01:04.4110

In [14]:
# Outputting both files to csv in Outputs folder
bike_2019_renamed_df.to_csv("Resources/2019_citibike_tripdata_cleaned.csv", index=False, header=True)
bike_2020_renamed_df.to_csv("Resources/2020_citibike_tripdata_cleaned.csv", index=False, header=True)